import { Component, OnInit, ChangeDetectorRef, ViewChild, ElementRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SapService } from '../../services/sap';

@Component({
  selector: 'app-finance',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './finance.html',
  styleUrls: ['./finance.css']
})
export class FinanceComponent implements OnInit {
  @ViewChild('dataStack') dataStack!: ElementRef;

  kunnr: string = localStorage.getItem('kunnr') || '';
  invoices: any[] = [];
  agingItems: any[] = [];
  memos: any[] = [];
  overallSales: number = 0;
  loading: boolean = true;
  isDownloading: boolean = false; 
  activeTab: 'finance' | 'aging' | 'memos' = 'finance';

  constructor(
    private sapService: SapService, 
    private cdr: ChangeDetectorRef 
  ) {}

  ngOnInit(): void {
    if (this.kunnr) {
      this.loadFinanceData();
    } else {
      this.loading = false;
    }
  }

  downloadInvoice(belnr: string): void {
    if (this.isDownloading) return;
    this.isDownloading = true;
    this.cdr.detectChanges();

    this.sapService.getInvoicePdf(belnr).subscribe({
      next: (data: any) => {
        if (data && data.EvStatus === 'S' && data.EvPdfBase64) {
          this.processBase64ToDownload(data.EvPdfBase64, belnr);
        } else {
          alert('Error: ' + (data?.EvMessage || 'PDF could not be generated by SAP.'));
        }
        this.isDownloading = false;
        this.cdr.detectChanges();
      },
      error: (err) => {
        this.isDownloading = false;
        alert('Could not connect to SAP to fetch PDF.');
        this.cdr.detectChanges();
      }
    });
  }

  private processBase64ToDownload(base64: string, filename: string) {
    try {
      const byteCharacters = atob(base64);
      const byteNumbers = new Array(byteCharacters.length);
      for (let i = 0; i < byteCharacters.length; i++) {
        byteNumbers[i] = byteCharacters.charCodeAt(i);
      }
      const byteArray = new Uint8Array(byteNumbers);
      const blob = new Blob([byteArray], { type: 'application/pdf' });
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `Invoice_${filename}.pdf`;
      link.click();
      window.URL.revokeObjectURL(url);
    } catch (e) {
      alert('Failed to process the PDF document.');
    }
  }

  switchTab(tab: 'finance' | 'aging' | 'memos') {
    this.activeTab = tab;
    this.cdr.detectChanges();
    if (this.dataStack) {
      this.dataStack.nativeElement.scrollIntoView({ behavior: 'smooth', block: 'start' });
      this.applyFocusHighlight();
    }
  }

  private applyFocusHighlight() {
    const el = this.dataStack.nativeElement;
    el.style.transition = 'outline 0.3s ease';
    el.style.outline = '2px solid var(--kt-gold)';
    setTimeout(() => el.style.outline = '2px solid transparent', 800);
  }

  loadFinanceData() {
    this.loading = true;
    const formattedKunnr = this.kunnr.padStart(10, '0');

    this.sapService.getFinanceSheet(formattedKunnr).subscribe({
      next: (data: any) => {
        // Map each array with the updated flexible mapper
        this.invoices = this.mapSapResponse(data?.EtInvoices);
        this.agingItems = this.mapSapResponse(data?.EtAging);
        this.memos = this.mapSapResponse(data?.EtMemos);
        
        const sales = data?.EvOverallSales;
        this.overallSales = sales ? parseFloat(sales) : 0;

        this.loading = false;
        this.cdr.detectChanges();
      },
      error: (err) => {
        this.loading = false;
        this.cdr.detectChanges();
      }
    });
  }

  private mapSapResponse(wrapper: any): any[] {
    if (!wrapper || wrapper === "" || (typeof wrapper === 'object' && Object.keys(wrapper).length === 0)) {
      return [];
    }

    let rawItems = wrapper.item || wrapper;
    // Handle cases where SAP returns a single item object instead of an array
    const items = Array.isArray(rawItems) ? rawItems : (rawItems ? [rawItems] : []);

    return items.map(item => {
      const normalized: any = {};
      Object.keys(item).forEach(key => {
        const upKey = key.toUpperCase();

        // 1. Handle Document Numbers (BELNR is standard, but VBELN is used in Billing)
        if (upKey === 'BELNR' || upKey === 'VBELN') {
          normalized['Belnr'] = item[key]?.toString();
        } 
        // 2. Handle Dates (BLDAT is Doc Date, FKDAT is Billing Date)
        else if (upKey === 'BLDAT' || upKey === 'FKDAT' || upKey === 'BUDAT') {
          normalized['Bldat'] = item[key];
        }
        // 3. Handle Amounts (WRBTR is Amount in Local Currency, NETWR is Net Value)
        else if (upKey === 'WRBTR' || upKey === 'NETWR') {
          normalized['Wrbtr'] = item[key];
        }
        // 4. Handle Currency
        else if (upKey === 'WAERS' || upKey === 'WAERK') {
          normalized['Waers'] = item[key];
        }
        // 5. Pass through specific Aging/Memo keys
        else if (['BUCKET', 'TYPE', 'AGING'].includes(upKey)) {
          normalized[key.charAt(0).toUpperCase() + key.slice(1).toLowerCase()] = item[key];
        }
        // 6. Default Fallback
        else {
          const pascalKey = key.charAt(0).toUpperCase() + key.slice(1).toLowerCase();
          normalized[pascalKey] = item[key];
        }
      });
      return normalized;
    });
  }
}